### ISSUE TITLE
Migrate messages to a .lang file

### ISSUE THREAD

**Issue by JosTheDude** [smuddgge/SmUtility#3]
That way I can make translations :)

**Comment by Smudgge** [comment]
Hey, thanks for reaching out and suggesting this feature! 

Im unsure how this would work effectively however. The `commands.yml` contains most of the messages sent to the player, and they are organised by command. What I could do is split some of the messages in the `messages.yml` that would make more sense to be in a lang file. Yet, this would be a new config file rather than replacing. Unless there is a better reason for a new lang file for some of the messages, I think its better to just create translations of the current two configs :3

**Comment by JosTheDude** [comment]
Alright :3
